apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  namespace: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
        - name: demo2
          image: hello-demo2:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo2
  namespace: demo2
spec:
  selector:
    app: demo2
  ports:
    - name: http
      port: 80
      targetPort: 8080
